### ISSUE TITLE
Params type conversion

### ISSUE THREAD

**Issue by georgyfarniev** [iyobo/koa-ts-controllers#4]
If I supply `@Params('id') id: number`, then it should be converted to number. A good example can be found in type-graphql library.

**Comment by iyobo** [comment]
Very true. Will add this in shortly

**Comment by iyobo** [comment]
Fixed in v1.3.6 for number primitives only. 
Published to npm.

Most fields come in as strings. Other primitives are boolean and number.

For number, An item can either be a number or NAN, so that's easy to cast.

For The boolean, however, is more nuanced and open to interpretation of what a true or a false is depending on expected input.

**Comment by iyobo** [comment]
Fixed in v1.3.6 for number primitives only. 
Published to npm.
